
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYktBTVRoVVpXdkV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1ERXdNekUwTlRkYUZ3MHpOVEF6TXpBd016RTVOVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURQVTEzV25WaUw2WjNWSmJENHBqTFN6WHNyL015M013aHQvY1ZzQzY1cFRpZG0ycHVuOEZ0aWI5aTQKcGpLV3ZrZEJmZkF5OU1LWUgzTGdTbSsyQmhCT0xnbVo0M2JYTWwvYzVrOUZyOW5oOGE1Mmo1VWtpdHdvT25BcQozQ2ZUSmtRZHg5ZHFJenMzSDZVbS9KTWNaYmRDL1hzVXRXZisybUg1NThJbDZTMjVPSXFBUHM3bTBPdXlsUjR0CmtzVFBEbmRsQzVnMTRWZ3FpeHpwaFdrM0E3MXo5dDRKZU1GMG91WHVlK2pYNGp0SjAxNUY3cjA1VFpFYkoyNE0KbjNOR2hDaGtiamllbkJERGpmOTREYmpGNVQzYWVzQmovRHd0NEhqcER0WnlUdkRuRHF0Z25URXNFN2FjMzAzaAp3Z2cxalZsWlYvWGlEVjBLazhQbDJSZFM5VUNWQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRKzRRREtaQW1XSFVtK3RmdkRaYzNMYnN0ZGFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1JaaTY0R04yRwo4OEZPOWZUc0FwbU1SNC9vRlM1bFlDWFRrZ1cwa2FLemR3TmJBVnc3M0IvREdsdE1LeTRkUTNBemlvZVlaMU9VClpaVHYvZlpEYlUyQ3MwNWhUWmN3QTM4VTVTMVpudk10WUxDS2RlWm9pckxjRHBuSTNhd29kM3cxd0VxekVaMmkKRmNlNHhrUUNlc3Y3RDhkTXFsb3dxOUpuOURDRDlLUzFoNnJEN25PaUtrd2JoL1JaUklaZUc4Y0VMWDMvUWpnMgpseFlDUEUyTHozKy9tZkxHTE1nNXh6d3ZxUERGWHo1ZFNuNnlCcUM0UkZMK1pwV1pjcWhiajNCQlcyUVUveksrCk0xTEZpSkY4RGRwb2U3MWpENWFLajNUUm44L25mUHVzd1hNYU93UzJ6U3hHMExKaFYwU3NvclFLN3ZhSENCY28KazV0N0Z6L1ZETmRiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5d52b8b0-0041-475d-a710-c57c5c03db73.us-west-2-gw.linodelke.net:443
  name: lke388297

users:
- name: lke388297-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjN6bVI4dmFfNUJiU2xaMmxFOW1UQkpyUmh4b0VJMTc0bUFWNFVJUmtON3MifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNG5mOHoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNTU0NGM1ZDUtZjQ5NC00OWU2LTgxODktZmQzZjQ5ZWZmNzUyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.moU_cqBviVuUWKiC3WG56smXBMw_uQhOF7lxGirL_9-BKL5pN7AWPp_iiTGPyY56bagSoSUoFH4UOi03gbtf_gnRKc3JB0Dm-SK01q68SHRICm3hTh45ZUFYjswVM0njZB1LQINg6ondsOaYBmCRYBTErel0xP0WtFDUT38UGvmbxfI3PhTaUn96Tu54a9llcJIboLhQfZo2W-GtjJCby9GptzA-Q0qC3tIsTgpvepTXaRxhgn7oZAzghSo6mVVIa7KkIVG3dh2HAaRCMmRs7WpaiLlSHBarCm6YBIKJLNsDG32WqGaxNBfxhRIDjbIyXyKMMW0MUjxCPMjtqEtMIw

contexts:
- context:
    cluster: lke388297
    namespace: default
    user: lke388297-admin
  name: lke388297-ctx

current-context: lke388297-ctx
