
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYUduNHlUSWVWYjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1ERXdNek01TlRoYUZ3MHpOVEF6TXpBd016UTBOVGhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNwOEtWOEdhTU0yekVHYzI5amMvQmp2VUl4OWtvMk4wbXMwbjZseWo3YldNWUxxNFkvbmVxdC9tcjkKVFVnWDhzbmxMcjBKUXhRTmRSM3BFcWNDamxKc1I2ZW5VbVZhR3ltcFUreHI0VURjbTMxR1RzZUlHVVJUOFQ5eApJRkszUitzNDVoZ21vOXIzb2Fwa2RvRkpLcHBwZ3AvVUhlU3JpaFU3bGhhclZxYnRtUUtsenpNTkJWZjZ3Y2NyCmxkWXhoYjA0Z1NPbjZwaDRVOE5MQ0M4MDdFK1JnaE9hZjZzd1pmckZnQ3BubUhzWi9WZ25JMG9mRzFSeEhNSEYKcW1DY1VmZnY2djBMTFRLcFFWb1lGOE9VcmpiNTE2M25CWnFGSjU5Kyt5V01TN2RQYUMrWGlGRWh0TG1RQlJqMwpmcVlmZnlueS8rVkx1Rk5uWG9qTEhmNlhxdm1KQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRcE9BRGlhTG5KZ2ttNzIzV0UwYWV5UWNTM2NEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2I1TzVnOWJvUwpVT2x4SFNKdjNLUUkwdFVqcWozdG5lWG4ySDBhNFlKaTdlM0V0ZTdvMGU0d2NRWjI0RG9sODNIZm12R0xKbWtUCnRPOFRGT0VLV3Nlc0JQYXBRM0dXdkx4MHNIaTF3bUN5SVF0amRsMlRXUUQ2SUlObCtGLzBDM01VT2YzWGxvM04KRVVzc2pKWjhxMVppRVRhTytLMTZNeElQZVREeXVpWUllaENyOGVqVDJ3SlN5Q1BoTks4ZnF4V1ZVVHJsQS9RUgovTkFGT1BtWE9VcG12WHhzUmJBU1J2TmZ3UDViYS9PallXYWhjU0I3MC9xVDJRR0owQzdPOEtoQXdjMmJkMEYrCk5rS3pXeFRoWEg2SXU1Qm5hc0tlV1NxS01JQXZSQWoyTzBkcXlwL2V5aUxjNEM5Z3lwYkprMyt5MU5xVW9OSTkKUUtubDd4YlcvZGxiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0bcbefd0-f045-430a-a2e0-4ed8d39872dd.us-east-3-gw.linodelke.net:443
  name: lke388315

users:
- name: lke388315-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkR3WW5tTWloTVRmMWhwek9FWkh0Z0JMOGRjTjVtWHNjVmZveU1YeXBjNE0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tMjJrc2MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTZkMjk3OWMtYmM5ZC00MDQxLWFmMTYtMTg4NDYyMGRmYTJiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.wzUSex_n3OfmCn3SsMbTow-Qh2qjmixw2iSQjhEX3-IjiGgeNdry03FCPUoaFr-dZhbzCegbp_w29NPjOl9uyD4WVLzsVWc9rUajkgq4jyC-oUotUPBzPwStvEPiWbYg9m4PWpyGjvLvMDgJBAgEiD4E6hkrMgxShssosnDJBId3Gje6-rxCNtaINmWnzCOZPRFL89XCE4X_h3cEy1SVw2TC_XSP_j8zuCi_OtpWIQI-HL0_UxeKOPFKmwkYEOfNdf3eJ_h_t5tohTa2Kt14GlnJ6Lf_-po5s8EGHlaojj9X5aLDqCtQ2SmZ4ZBfPGW10xmoBFSKO0SRPaQRpEBJWQ

contexts:
- context:
    cluster: lke388315
    namespace: default
    user: lke388315-admin
  name: lke388315-ctx

current-context: lke388315-ctx
