
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJS1NlMlZJWHhmVnd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBME1ERXdOVE13TXpsYUZ3MHpOVEF6TXpBd05UTTFNemxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUR3OHNmNmwyWlg3N2JxcW1hbXg1T2ZCSndQcFk5UjRMMzhOMjB4b3dhNVJyZzFVQVJvSDBuSWt1UzQKczVZMk9VdlMyd3BSSzUzYnhtYXNGeXZrZTcyNnRFT1ZSbkdYdUVBMFpvU0ZtZHFSWFk5VGNqTVI0UGZHQlF0NQpjVjhXV2FqOHNuSUVmak9aclhEVmZsRFpBUnZYNnYzaUFVWXg5UDRBVTFQVmpNNkhBYWFJQnlFSnFmb2duOStQCngxM25JQkVBM1NhdDRMSnJwTERUVjdIUTMvK1ZGdmhJTU9tRzVIa2xWOHh0VVZubmZ2THI3dG84YlJ0YWlxdjIKZzJiQUdtM21ESUo4c2E0NFdSNTFKQnZLcGt4Yk5Fb2h4K1IrcFRsV1VVa0lhTXA4S3FNS0s5ZmhwRm5MTWl5cgpibDVCNFpKUEFEZFdobDZiTzV0VnVZTHVic24vQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUHNkRk5aeFJ5YlpzSHZWS0hmSFRRTEFJS0FUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQk9NaVZPcW5VeApCdTJYUWhhQlVKbEdXYzdqcWhhNVBkcDVsWjFqSytLSmJrV0VVSWtmYzNCbDJ0VEpycUFqUlpSOTJYR2JxZS9XCjN4eEVCcUdnbUFjc1d1MjNhYkplaC94bXM0TFlhUmNxRVZxTCtYenA4bUZIMy9DSGd6TGxjYUdheVYzWEFpdXQKWVZvR0hwRkRtZHJKWTRBakg0eFN6R1JvaHdDNEt1VFF1eVpYRUZKOC93NUsvYjNNTERxbyt3VE8wOFRUOEhlSwpXY2dyMHpqRVhvTkdaUlFOb0twOThRd2plOUwxc2ttY3lqUTR2cGNyZ044c0pEa2dKaHFEMFpmM2JTczZsUS9BClBESkQ4QllZeXRQNlRBdXYyODJDK1Z3dFB0MVozZ3Zjam9zZVRLZTNwcVlySVhtMFJGVVV3VHZwRllqOERVem4KejlOcnRvVHVYaDN4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://6c5acfb4-2d24-410a-b12b-2a1ca3a68583.us-east-3-gw.linodelke.net:443
  name: lke388383

users:
- name: lke388383-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjFGNXA5LW9QS2JwSGJ2NFEtTTNLaVpsbFdrV2hsd0cwYm1DZGc3ZFZUMVUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbHY4eHYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmFiNmE2ZDAtNDczMC00ZTk5LWI5ZmQtNjdkNWIwYzZmNmFhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.mIdYxrN2eNZrGshelZtEthjZUTKEnkhmzW3X3uNcRXL6uMFzGh9q13F2LSspGtbMmoAT4QSFwJ2yT6DQBR4ZQMX8jTYCR4hAsIxCYsjPUVFzxeTOy_tF6tAFKOZCpVyVYyhQX4OOf1vdKPf6iRl9zg0uUFIVgTRbWz2n8ZPqJ4oxAOEu1vIv_0e0i1VR5vEOvbuOxM8c4sd1V0OFXLU733HEgdZ5uY8Y2EkZRRccFWbYcCT2pMAUrlFrQfDLrrB2-BEXbM5Q_GapIIZ0PsN4phg3pM4NGABO616PmEb8PEccYnCpQkUlvA5T-71WVyLYw1d3izcAe2BDQgCNHZGMHw

contexts:
- context:
    cluster: lke388383
    namespace: default
    user: lke388383-admin
  name: lke388383-ctx

current-context: lke388383-ctx
